# -*- coding: utf-8 -*-
"""train_mlflow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ydruyJWvIzNmy2F1jcvrdHlzGzH1Xtzp
"""

!pip install mlflow

import os
import joblib
import mlflow
import mlflow.sklearn
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)


# ============================================================
# SETTINGS
# ============================================================

DATA_PATH = "/content/aiml_training_data.csv"

# CHANGE THIS if your target column has a different name
TARGET_COLUMN = "intent"

MODEL_DIR = "models"
OUTPUT_DIR = "outputs"

os.makedirs(MODEL_DIR, exist_ok=True)
os.makedirs(OUTPUT_DIR, exist_ok=True)


# ============================================================
# LOAD DATA
# ============================================================

print("\nLoading processed dataset...")

df = pd.read_csv(DATA_PATH)

print("Dataset shape:", df.shape)
print("Columns:", list(df.columns))


# ============================================================
# CHECK TARGET
# ============================================================

if TARGET_COLUMN not in df.columns:
    raise ValueError(
        f"\nTarget column '{TARGET_COLUMN}' was not found.\n"
        f"Available columns are:\n{list(df.columns)}\n"
        "Change TARGET_COLUMN in train_mlflow.py."
    )


# ============================================================
# FEATURES AND TARGET
# ============================================================

X = df.drop(columns=[TARGET_COLUMN])
y = df[TARGET_COLUMN]

print("\nTarget distribution:")
print(y.value_counts())


# ============================================================
# TRAIN / TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining samples:", len(X_train))
print("Testing samples:", len(X_test))


# ============================================================
# IDENTIFY DATA TYPES
# ============================================================

numerical_columns = X.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

categorical_columns = X.select_dtypes(
    include=["object", "category", "bool"]
).columns.tolist()

print("\nNumerical columns:")
print(numerical_columns)

print("\nCategorical columns:")
print(categorical_columns)


# ============================================================
# PREPROCESSING
# ============================================================

numerical_pipeline = Pipeline([
    (
        "imputer",
        SimpleImputer(strategy="median")
    )
])


categorical_pipeline = Pipeline([
    (
        "imputer",
        SimpleImputer(strategy="most_frequent")
    ),
    (
        "encoder",
        OneHotEncoder(handle_unknown="ignore")
    )
])


preprocessor = ColumnTransformer([
    (
        "numerical",
        numerical_pipeline,
        numerical_columns
    ),
    (
        "categorical",
        categorical_pipeline,
        categorical_columns
    )
])


# ============================================================
# MLFLOW
# ============================================================

os.environ["MLFLOW_ALLOW_FILE_STORE"] = "true"
mlflow.set_tracking_uri("file:./mlruns")

mlflow.set_experiment(
    "credit-risk-model-tuning"
)


# ============================================================
# HYPERPARAMETER CONFIGURATIONS
# ============================================================

configs = [

    {
        "name": "configuration_1",
        "C": 0.1,
        "solver": "liblinear",
        "class_weight": None
    },

    {
        "name": "configuration_2",
        "C": 1.0,
        "solver": "liblinear",
        "class_weight": "balanced"
    },

    {
        "name": "configuration_3",
        "C": 10.0,
        "solver": "liblinear",
        "class_weight": None
    }

]


# ============================================================
# EXPERIMENT RESULTS
# ============================================================

results = []

best_f1 = -1
best_model = None
best_config = None


# ============================================================
# TRAIN EACH CONFIGURATION
# ============================================================

for config in configs:

    print("\n")
    print("=" * 60)
    print("Running:", config["name"])
    print("=" * 60)

    with mlflow.start_run(
        run_name=config["name"]
    ):

        # ----------------------------------------------------
        # MODEL
        # ----------------------------------------------------

        classifier = LogisticRegression(
            C=config["C"],
            solver=config["solver"],
            class_weight=config["class_weight"],
            max_iter=1000,
            random_state=42
        )


        model = Pipeline([
            (
                "preprocessor",
                preprocessor
            ),
            (
                "classifier",
                classifier
            )
        ])


        # ----------------------------------------------------
        # TRAIN
        # ----------------------------------------------------

        model.fit(
            X_train,
            y_train
        )


        # ----------------------------------------------------
        # PREDICT
        # ----------------------------------------------------

        predictions = model.predict(
            X_test
        )


        # ----------------------------------------------------
        # METRICS
        # ----------------------------------------------------

        accuracy = accuracy_score(
            y_test,
            predictions
        )

        precision = precision_score(
            y_test,
            predictions,
            average="weighted",
            zero_division=0
        )

        recall = recall_score(
            y_test,
            predictions,
            average="weighted",
            zero_division=0
        )

        f1 = f1_score(
            y_test,
            predictions,
            average="weighted",
            zero_division=0
        )


        # ----------------------------------------------------
        # LOG PARAMETERS
        # ----------------------------------------------------

        mlflow.log_param(
            "model",
            "LogisticRegression"
        )

        mlflow.log_param(
            "C",
            config["C"]
        )

        mlflow.log_param(
            "solver",
            config["solver"]
        )

        mlflow.log_param(
            "class_weight",
            str(config["class_weight"])
        )

        mlflow.log_param(
            "test_size",
            0.20
        )

        mlflow.log_param(
            "random_state",
            42
        )


        # ----------------------------------------------------
        # LOG METRICS
        # ----------------------------------------------------

        mlflow.log_metric(
            "accuracy",
            accuracy
        )

        mlflow.log_metric(
            "precision",
            precision
        )

        mlflow.log_metric(
            "recall",
            recall
        )

        mlflow.log_metric(
            "f1_score",
            f1
        )


        # ----------------------------------------------------
        # LOG MODEL
        # ----------------------------------------------------

        mlflow.sklearn.log_model(
            model,
            "model",
            skops_trusted_types=[
                "numpy.dtype",
                "sklearn.compose._column_transformer._RemainderColsList",
            ]
        )


        # ----------------------------------------------------
        # SAVE RESULT
        # ----------------------------------------------------

        results.append({

            "configuration": config["name"],

            "C": config["C"],

            "solver": config["solver"],

            "class_weight": config["class_weight"],

            "accuracy": accuracy,

            "precision": precision,

            "recall": recall,

            "f1_score": f1

        })


        # ----------------------------------------------------
        # DISPLAY
        # ----------------------------------------------------

        print(
            f"Accuracy : {accuracy:.4f}"
        )

        print(
            f"Precision: {precision:.4f}"
        )

        print(
            f"Recall   : {recall:.4f}"
        )

        print(
            f"F1 Score : {f1:.4f}"
        )


        # ----------------------------------------------------
        # CHECK BEST MODEL
        # ----------------------------------------------------

        if f1 > best_f1:

            best_f1 = f1

            best_model = model

            best_config = config.copy()


# ============================================================
# SAVE EXPERIMENT RESULTS
# ============================================================

results_df = pd.DataFrame(
    results
)

results_path = os.path.join(
    OUTPUT_DIR,
    "mlflow_experiment_results.csv"
)

results_df.to_csv(
    results_path,
    index=False
)


# ============================================================
# SAVE BEST MODEL
# ============================================================

best_model_path = os.path.join(
    MODEL_DIR,
    "best_model.joblib"
)

joblib.dump(
    best_model,
    best_model_path
)


# ============================================================
# SAVE BEST CONFIGURATION
# ============================================================

best_config_path = os.path.join(
    OUTPUT_DIR,
    "best_configuration.txt"
)

with open(
    best_config_path,
    "w"
) as file:

    file.write(
        "BEST MODEL CONFIGURATION\n"
    )

    file.write(
        "=========================\n\n"
    )

    for key, value in best_config.items():

        file.write(
            f"{key}: {value}\n"
        )

    file.write(
        f"\nBest F1 Score: {best_f1:.4f}\n"
    )


# ============================================================
# FINAL RESULTS
# ============================================================

print("\n")
print("=" * 60)
print("EXPERIMENT COMPARISON")
print("=" * 60)

print(
    results_df.to_string(index=False)
)


print("\n")
print("=" * 60)
print("BEST CONFIGURATION")
print("=" * 60)

print(
    f"Configuration : {best_config['name']}"
)

print(
    f"C             : {best_config['C']}"
)

print(
    f"Solver        : {best_config['solver']}"
)

print(
    f"Class Weight  : {best_config['class_weight']}"
)

print(
    f"Best F1 Score  : {best_f1:.4f}"
)


print("\nSaved files:")

print(
    f"- {best_model_path}"
)

print(
    f"- {results_path}"
)

print(
    f"- {best_config_path}"
)

print("\nCheckpoint 3 training complete.")